### ISSUE TITLE
add automatic hyperlinking?

### ISSUE THREAD

**Issue by derekeder** [derekeder/csv-to-html-table#1]
Perhaps we can detect links and automatically add hyperlinks with this thing: https://github.com/SoapBox/jQuery-linkify

**Comment by stephenturner** [comment]
+1 to this :+1:

**Comment by stephenturner** [comment]
I'm using this for my own project, and wrote [this Makefile in the project repo](https://github.com/stephenturner/biofiletypes/blob/gh-pages/Makefile) that scans a CSV for markdown links e.g. `[google](http://google.com)` and uses a perl regex to convert that to an HTML link. It also fixes what MS Excel destroys wrt line endings. Could probably extend this with a regex to look for bare URLs.

```perl
data = data/mydatafile.csv

all: 
	# fix line endings
	perl -pi -e 's/\r/\n/g; $$_.="\n" if eof' $(data)
	# get rid of blank lines
	perl -ni -e 'print unless /^$$/' $(data)
	# parse markdown links
	perl -pi -e 's@\[([^\[]+)\]\(([^\)]+)\)@<a href='\''$$2'\'' target='\''_blank'\''>$$1</a>@g' $(data)
```

**Comment by derekeder** [comment]
This is cool. I'm a huge fan of Make!

My only concern is ease of use. One of the really nice features of this project is its 100% javascript and HTML, and is intended to be easy for 'plug and play'.

I was thinking of doing a similar regex in Javascript. For the excel stuff, I was thinking of using this: https://github.com/SheetJS/js-xls and https://github.com/SheetJS/js-xlsx

**Comment by freddymartinez9** [comment]
In `csv_to_html_table.js`  made the following edits  
`csv_data[row_id][10]` = linkify(csv_data[row_id][10]);` where linkify is a JS function 
```
function linkify(inputText) {
    //URLs starting with http://, https://, or ftp://
    var replacePattern1 = /(\b(https?|ftp):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/gim;
    var replacedText = inputText.replace(replacePattern1, '<a href="$1" target="_blank">Text of Link Request</a>');
    return replacedText
}
```

However this implementation is not very efficient for many columns, in fact you have to define it for each column. It is a way to hack around this. @derekeder actually helped me write this.

**Comment by derekeder** [comment]
Hey all, I ended up adding a generic way to pass in custom formatting functions and apply them to specific columns, like so:

``` html
<script>

  //my custom function that creates a hyperlink
  function format_link(link){
    if (link)
      return "<a href='" + link + "' target='_blank'>" + link + "</a>";
    else
      return "";
  }

  //initializing the table
  CsvToHtmlTable.init({
    csv_path: 'data/Health Clinics in Chicago.csv', 
    element: 'table-container', 
    allow_download: true,
    csv_options: {separator: ',', delimiter: '"'},
    datatables_options: {"paging": false},
    custom_formatting: [[4, format_link]] //execute the function on the 4th column of every row
  });
</script>
```

Hope this helps!

**Comment by freddymartinez9** [comment]
This is a good implementation thanks Derek.

**Comment by derekeder** [comment]
👍
