### ISSUE TITLE
Table field not showing

### ISSUE THREAD

**Issue by gracetchome** [derekeder/csv-to-html-table#11]
This is a great feature!
I downloaded it, but when I view the index page the table does not show up - is there anything else that needs to be done?

![screen shot 2016-02-22 at 9 55 02 am](https://cloud.githubusercontent.com/assets/17409840/13221672/9800dc84-d94a-11e5-83c7-5b010704d19b.png)

**Comment by derekeder** [comment]
Looks like it's a javascript error. You can see what the error is by following these instructions: https://github.com/derekeder/csv-to-html-table#common-issuestroubleshooting

Also, did you modify the code at all after you downloaded it? What operating system & browser are you using?

**Comment by gracetchome** [comment]
I didn't modify the code at all - I just downloaded it and tried to view it in a browser. I'm trying it on a mac in google chrome, safari and firefox. And it hasn't worked. I've also tested it on a PC. Please advise. Thanks!

**Comment by derekeder** [comment]
Are you running the site with this command?

`python -m SimpleHTTPServer`

https://github.com/derekeder/csv-to-html-table#4-run-it

If you just open `index.html` directly into your browser, the table will not properly load.

**Comment by gracetchome** [comment]
no...
Does it have to be done through github or can i just download the demo and work off the files and code from my computer using an editor like dreamweaver?

**Comment by derekeder** [comment]
The code will work on your computer, but you need to run it through a web server application. Python has a simple one that I recommend, but you can use others too.

Looks like Dreamweaver has this feature: https://www.adobe.com/devnet/archive/dreamweaver/articles/setup_testing_server.html

**Comment by gracetchome** [comment]
Okay, thank you for your help!
