### ISSUE TITLE
Unicode UTF-8 Charset bug

### ISSUE THREAD

**Issue by ocvninfo** [derekeder/csv-to-html-table#12]
I noticed that csv-to-html-table doesn't support Unicode UTF-8 Charset .
**example:**
Accéssorius (true display)
Acc�ssorius (wrong display)

Hope this will be fixed ASAP!
Thanks !

**Comment by derekeder** [comment]
@ocvninfo I haven't been able to reproduce this. Could you point me to a CSV file this happens on?

**Comment by axi92** [comment]
[test.zip](https://github.com/derekeder/csv-to-html-table/files/1554248/test.zip)

**Comment by dupls** [comment]
I got around this with Notepad++
1. Use notepad++ to create a new UTF-8 text file - myfile-UFT8.csv
2. Save existing myfile.xls spreadsheet as csv - myfile.csv
3. Open myfile.csv in notepad++, select all content and copy.
4. Paste into myfile-UFT8.csv.
5. Save
And upload into the data folder. 
Voila!

**Comment by JinInRage** [comment]
I had got the same problem. I found out it's not the fault of the javascript code. It's the fault of the server serving the csv file. It responds with mime type: "text/csv", but it has to be "text/csv; charset=iso-8859-1"
In my case I had to add "AddCharset ISO-8859-1 .csv" to the Apache config. So with this solution, you don't have to convert the csv files from ISO-8859 to UTF-8.

**Comment by derekeder** [comment]
closing as the solution is unrelated to this repository. thanks @ghost for posting a fix!
