### ISSUE TITLE
How to add total/sum of any given column?

### ISSUE THREAD

**Issue by tshrinivasan** [derekeder/csv-to-html-table#22]
Thanks for the great tool.

We use this to display the total download counts of free ebooks on the site http://FreeTamilEbooks.com

http://freetamilebooks.com/htmlbooks/download-report.html

We want to display the total downloads from the site. i.e to show the sum of the last column.

How to show the total ?

Thanks.

**Comment by derekeder** [comment]
@tshrinivasan cool!

Unfortunately, there's no simple way to do this. You'll need to go into `js/csv-to-html-table.js` and modify the code.

* go into the [for loop that renders the table](https://github.com/derekeder/csv-to-html-table/blob/master/js/csv_to_html_table.js#L30) and track the sum for each column you want
* add a `<tfoot></tfoot>` section to the bottom of your table and add the summed values to it

**Comment by tshrinivasan** [comment]
Thanks for the reply.

Will explore on that.

is it possible to integrate the example shown here?
https://datatables.net/examples/advanced_init/footer_callback.html

**Comment by derekeder** [comment]
@tshrinivasan yes, you could write the footercallback function and then pass it into the `datatables_options`. That would probably be the least complicated solution.

**Comment by derekeder** [comment]
Oh, and if you figure out something along these lines that works generically, I'd welcome a pull request with an update to the README.md with instructions on how others can do this.

**Comment by tshrinivasan** [comment]
I cant play with javascript. Tried various options. No luck.
Added the sum operation and timestamp in the python code itself, to write on separate html file.
Showing that html files as iframe above the table.
Thus I solved the issue.

Thanks.
