### ISSUE TITLE
How to sort the table on any given column?

### ISSUE THREAD

**Issue by tshrinivasan** [derekeder/csv-to-html-table#23]
The table is sorted by the first column now. But I want it to be sorted on the last column in reverse order.

Help to make this.

Thanks.

**Comment by derekeder** [comment]
@tshrinivasan look at Datatables documentation on sorting: https://datatables.net/examples/basic_init/table_sorting.html

You can pass in the Datatables configuration to the `datatables_options` when initializing the table

**Comment by tshrinivasan** [comment]
CsvToHtmlTable.init({
        csv_path: 'data/all_files.csv', 
        element: 'table-container', 
        allow_download: true,
        csv_options: {separator: '~', delimiter: '~'},
        datatables_options: {"paging": true},
        "order": [[ 5, "desc" ]]
  
});

I use like this.
But still no change. Table is sorted by 1st column only.
any clues?

**Comment by derekeder** [comment]
The options you pass in need to be properly formatted as an object, like so:

```javascript
CsvToHtmlTable.init({
    csv_path: 'data/all_files.csv', 
    element: 'table-container', 
    allow_download: true,
    csv_options: {separator: '~', delimiter: '~'},
    datatables_options: {"paging": true, "order": [[ 5, "desc" ]]}
});


```

**Comment by tshrinivasan** [comment]
super. it worked. Thanks a lot.
