### ISSUE TITLE
Dynamic refresh

### ISSUE THREAD

**Issue by pointer2array** [derekeder/csv-to-html-table#26]
It would be very useful to have the page update if the underlying data changes. I am not sure the best way to do it.

**Comment by derekeder** [comment]
@pointer2array the way to do this would be to figure out a way to update your underlying CSV. As long as the URL stays the same, the HTML table will update.

This kind of update task can be done in an almost infinite number of ways, and so is outside the scope of this project.

**Comment by pointer2array** [comment]
@ derekeder . Thank you for a quick response. I was thinking of refresh the page without manually refreshing the page oh the browser. Assuming the data is changed somehow and the url to the csv file remains same. 

Thank you.
