### ISSUE TITLE
Table order by date

### ISSUE THREAD

**Issue by ernestogarj** [derekeder/csv-to-html-table#28]
Hi There 

Fantastic project! , I have one problem I have a table with two colums Date and Name in the csv are order by date correctly but when i run it I have a problem for example We have dates with differents months for example 1/11/2016 and 26/10/2016 appear before 1/11/2016 than 26/10/2016 I think that it only consider the day and not the month, could I fix it change some paramets?

Thanks

**Comment by derekeder** [comment]
@ernestogarj thanks!

We're using DataTables to do sorting. Looks like you could use this sorting plugin: https://datatables.net/plug-ins/sorting/date-uk

Once you have that added, you can set the configuration in `datatables_options`
