### ISSUE TITLE
Does the tool accept other delimiters such as semicolons ?

### ISSUE THREAD

**Issue by blaquans** [derekeder/csv-to-html-table#3]
French speaking people often prefer semicolon delimited files to comma separated files. See for instance this [file](https://www.data.gouv.fr/en/datasets/liste-des-boites-aux-lettres-de-rue-france-metropolitaine-et-dom-1/) on DataGouvFr. 

Is it possible to adapt the tool to semicolon delimited files ?

**Comment by connorsb** [comment]
Looks like you can change the separator and delimiter in this regex block right here: https://github.com/derekeder/csv-to-html-table/blob/master/js/jquery.csv.min.js#L3

**Comment by derekeder** [comment]
@connorsb yup good call. I will add a configuration so you can pass in options to jQuery CSV for separator & delimiter.
