### ISSUE TITLE
complex header

### ISSUE THREAD

**Issue by mattijn** [derekeder/csv-to-html-table#32]
Reading DataTables documentation it seems possible to have a double row header, but I cant figure it out how this can be configured from within this great utility. It seems not possible, or I'm missing something?

https://datatables.net/examples/basic_init/complex_header.html

**Comment by derekeder** [comment]
@mattijn we dynamically generate the header based on the column names in the CSV. You'd need to override this in https://github.com/derekeder/csv-to-html-table/blob/master/js/csv_to_html_table.js#L20 to add the additional header row to the rendered HTML.

Looks like after you do that, DataTables will work as expected.
