### ISSUE TITLE
Refresh html content after csv changed

### ISSUE THREAD

**Issue by ezsosza** [derekeder/csv-to-html-table#36]
Hi,

Nice tool, i really like it!
I have noticed, that after the csv file has been updated, and in the browser the page has been refreshed, the old csv content is displayed still. Deleting the browser cache seem to solve the issue, however, how could the page (javascript) ensure that always the actual content is displayed?
Thanks.

**Comment by campeaux** [comment]
Add a random string generator after the csv file extension and that will prevent most browsers from caching the file—the browser will think it's calling on a new file all the time—may be bad for large files that you actually want to cache.

Example of it rendered in html:

```
CsvToHtmlTable.init({
        csv_path: 'data.csv?v=030aj20kska2',
        ...	
      })
```

Better example:
[StackOverflow](http://stackoverflow.com/questions/7413234/how-to-prevent-caching-of-my-javascript-file)

**Comment by ezsosza** [comment]
Thanks, This should work.
