### ISSUE TITLE
change destination of csv file

### ISSUE THREAD

**Issue by kowalendo123** [derekeder/csv-to-html-table#37]
when i try change destination of csv file with option form i have only error funcion() not found

``<body>
    <div class="container-fluid">

      <h2>Tabele Wydawcow</h2>
      <div class="form-group">
    <label for="choose_site">Wybierz strone</label>
    <select class="form-control" id="choose_csv">
      <option value="Health Clinics in Chicago.csv" id="Health_Clinics_in_Chicago">Health Clinics in Chicago</option>
      <option value="fatty_acid_profiles.csv" id="fatty_acid_profiles">Fatty acid profiles</option>
    </select>
    <button onclick="funkcja">Try it</button>
  </div>
      
      <div id="table-container"></div>

    </div>

    <script type="text/javascript">
	
	function funkcja(csv)
	{
		var choose_csv = document.getElementById("choose_csv").value;
		var csv = "data/"+choose_csv;
		return csv;
	}
      function format_link(link)
	  {
        if (link)
          return "<a href='" + link + "' target='_blank'>" + link + "</a>";
        else
          return "";
      }

      CsvToHtmlTable.init(
	  {
        csv_path: 'funkcja', 
        element: 'table-container', 
        allow_download: false,
        csv_options: {separator: ',', delimiter: '"'},
        datatables_options: {"paging": false},
        custom_formatting: [[4, format_link]]
      });
    </script>
	
	
  </body>
</html>

**Comment by derekeder** [comment]
It looks like in your javascript you are setting the `csv_path` to the literal string `funkcja` instead of calling the function you wrote `funkcja()`. 

Also, the function you wrote should not require a parameter to call it. You should declare it as:

```javascript
function funkcja() {
   ...
}
```
