### ISSUE TITLE
Make multiple columns links

### ISSUE THREAD

**Issue by dawsonpaul** [derekeder/csv-to-html-table#38]
Hi, I've really tried everything I can think of to make multiple columns (as opposed to just one) use the format_link function.

I've tried 

          custom_formatting: [[0,8, format_link]],

And many other permutations. I want Column 0 and 8 to use the link function. Is this possible?

**Comment by uglygus** [comment]
This works:
`        custom_formatting: [[0, format_link], [8, format_link]]`

**Comment by dawsonpaul** [comment]
I tried that but the spreadsheet fails to load.

**Comment by speedlover** [comment]
Make sure to copy EXACTLY.
[[0, format_link], [8, format_link]]
You need the brackets around both, and dont miss any commas.
![capture2](https://cloud.githubusercontent.com/assets/21209299/26477585/b27f98ea-421a-11e7-896e-8176852d4a58.PNG)
^^^ My implementation which seems to work fine.

**Comment by derekeder** [comment]
looks like this was addressed. thx @speedlover 

closing
