### ISSUE TITLE
Quotation marks in CSV

### ISSUE THREAD

**Issue by uglygus** [derekeder/csv-to-html-table#39]
How to include quotation marks in the CSV?

I could change the delimiter but is there a way to escape quotation marks and have them be interpreted correctly?

This fails....
name,title
Mike,"CEO \\"sales\\""

*edit - getting quotes to show correctly on github. :)

**Comment by derekeder** [comment]
We parse CSVs using `jquery.csv`. This looks to be a relevant thread in their repo: https://github.com/evanplaice/jquery-csv/issues/43

Looks like quotes should be escaped with additional double quotes.

Mike,"CEO ""sales"""
