### ISSUE TITLE
chrome extension / webapp?

### ISSUE THREAD

**Issue by nealrs** [derekeder/csv-to-html-table#4]
I know you'll run into a CORS issue if you try to use a http link for the datasource, but why not rejigger this into a browser extension that can be used to browse CSVs without having to use Excel?

or, a webapp for datafiles that are <5mb?

**Comment by derekeder** [comment]
Cool idea, though probably outside the scope of this project. 

Have you seen [DataPipes](http://datapipes.okfnlabs.org/)? It does something similar as a hosted service.

**Comment by nealrs** [comment]
hadn't heard of DataPipes before, but that's pretty boss.
