### ISSUE TITLE
Custom formatting for multiple columns. (Solved)

### ISSUE THREAD

**Issue by speedlover** [derekeder/csv-to-html-table#45]
Ive tried doing [[2 format_dollar],[3, format_dollar]] which was suggested in a different issue thread, but that fails to load, I have also tried [[2,3, format_dollar]] which fails for obvious reasons and [[[2, 3], format_dollar]] which displays but doesnt do anything. 

Is there a way?

**Comment by speedlover** [comment]
Closing this issue, 
[[2 format_dollar],[3, format_dollar]] 
should be 
[[2, format_dollar],[3, format_dollar]] 
***Facepalm***

**Comment by derekeder** [comment]
sometimes, just writing it down solves the problem. 😸
