### ISSUE TITLE
How to skip first few rows?

### ISSUE THREAD

**Issue by pdctpa** [derekeder/csv-to-html-table#46]
Hi, Thanks for this awesome script. Will you be able to guide me how can I skip first 3 rows from the csv generated table.

**Comment by campeaux** [comment]
I don't think the custom formatting options will let you do this. You could run AWK server-side to remove the first three rows and generate a new CSV.

**Comment by derekeder** [comment]
I agree with @campeaux. Skipping rows should be addressed outside of this tool. You could also open up the CSV in Excel (or similar program) and save a version with the first 3 rows deleted.

using `awk` you could do something like this: 

```
awk '(NR>1)' my_file.csv
```

More documentation if you're interested: https://linuxhint.com/skip_line_awk/
