### ISSUE TITLE
Hide loading bar?

### ISSUE THREAD

**Issue by speedlover** [derekeder/csv-to-html-table#47]
Im trying to display a 1200 row csv (1200 row x 4 columns) which obviously takes a bit to load. (From almost instant to 5 seconds, depending on the computer). Ive been experimenting with having a loading animation or text to show that it is loading. 
Is there a way to use javascript once the table finishes generating to hide the loader?

What needs to be called:
`function hideloader(){ document.getElementById('hideme').style.display = 'none'; }`

**Comment by speedlover** [comment]
Found a solution - 
`<script> window.onload = function hideSmall() { document.getElementById('hideme').style.display = 'none'; }; </script>`

Because the table generating still counts as loading so this can only execute afterwards.

**Comment by derekeder** [comment]
Nice! Not something I'll include in the project, but good to know.
