### ISSUE TITLE
By Default Need to sort on particular colum

### ISSUE THREAD

**Issue by nouman05** [derekeder/csv-to-html-table#48]
Hey, Congratulation for nice effort,

I want to sort by default on particular column (Need to display sorted column by default). Is there any way, we can get this.

Thanks.

**Comment by watermelonma** [comment]
have you tried this method from the datatables faq?:
https://datatables.net/examples/basic_init/table_sorting.html
I think it suggests to add: "order": [[ 3, "desc" ]] in the customisable area of the table. I haven't tried but thought this may be it.

**Comment by nouman05** [comment]
Thank You watermelonma.
I have added following line
"order": [[ 7, "desc" ]] in datatables_options and its working fine for me.

datatables_options: {"paging": false, "order": [[ 7, "desc" ]]}

Thanks.
