### ISSUE TITLE
multiple tables on same page

### ISSUE THREAD

**Issue by matthijsberk** [derekeder/csv-to-html-table#49]
Is it possible to use this and get multiple csv's into separate tables on the same page? I can't get that to work.

**Comment by jgdwyer** [comment]
I was having the same issue, but just figured it out. If you are using the default index.html file create another container-fluid div item in the ``<body>``:
`<div class="container-fluid">
      <div id='table-container2'></div>
    </div>`
(Be sure to give the ``div id`` a different name than the original one). 
Then copy and paste the ``<script>`` field, but within CsvToHtmlTable.init, change the element entry to `'table-container2'` or whatever `div id` value you chose above:
`<script type="text/javascript">
      CsvToHtmlTable.init({
        csv_path: 'data/roto_stats.csv',
        element: 'table-container2', 
        allow_download: true,
        csv_options: {separator: ',', delimiter: '"'},
        datatables_options: {"paging": false}
      });
    </script>`

**Comment by matthijsberk** [comment]
Thanks, that works.
