### ISSUE TITLE
how to limit the number of rows

### ISSUE THREAD

**Issue by rgarimella9** [derekeder/csv-to-html-table#52]
i would like to list only 100 entries per page and a next button to go for next page when i am listing the csv content to table format.

rgarimella

**Comment by levaganak** [comment]
setTimeout( () => 
        $(document).ready(function(){
          $('#table-ID').dataTable()
        }), 5000);

**Comment by derekeder** [comment]
@rgarimella9 you can accomplish this by using the built-in paging in `DataTables`: https://datatables.net/reference/option/paging

Set the `paging` option to `true` in `datatables_options`:

```javascript
CsvToHtmlTable.init({
    csv_path: "data/Health Clinics in Chicago.csv",
    element: "table-container",
    allow_download: true,
    csv_options: {
        separator: ",",
        delimiter: '"'
    },
    datatables_options: {
        paging: true
    },
    custom_formatting: [
        [4, format_link]
    ]
});
```
