### ISSUE TITLE
Problem under firefox after unzip file

### ISSUE THREAD

**Issue by naltap** [derekeder/csv-to-html-table#55]
Hi,
i test csvtohtmltable with only unzip the file and open the html file.
do you know why with only unzip the file they have some problem only with firefox and not IE ?

with the web, there is no problem.
Nonetheless i have changed the function link to use the link behind the value row, and so not display the link.
If you are interested i will send the function.

Regards
NaltaP

**Comment by thierrysultana** [comment]
Hello
i have the same problem.
I'am  interested , you can send the function?.
Thx

**Comment by olar06** [comment]
Hello,
Same problem with Firefox. Work with the web demo and does'nt work with the unzip files or clones files.
I'am also interested. Can send you the function?
Many thanks :-)

**Comment by derekeder** [comment]
opening the `index.html` file directly in a browser will not work, as it needs to reference files using absolute file paths.

please follow the instructions on running the code locally: https://github.com/derekeder/csv-to-html-table#4-run-it
