### ISSUE TITLE
Transform - or format data

### ISSUE THREAD

**Issue by m-menon** [derekeder/csv-to-html-table#6]
Thanks for the excellent plugin. It works super well. Just wanted to check if there is some code that I can alter so that some formatting can be done? For example my datetime string is in unix / epoch time format and I want to display this in more user readable / friendly manner. Is there a way that I could access the rows when they are being processed so that I can transform the data? Thanks a ton

**Comment by derekeder** [comment]
I don't have anything in place to gracefully inject formatting, but you could follow the same pattern I described in #13.

Open to pull requests if you'd like to submit one!
