### ISSUE TITLE
Large CSV will be crashed...

### ISSUE THREAD

**Issue by Marow** [derekeder/csv-to-html-table#64]
My CSV doesnt load. 
If i load the Site, i doesnt see the table and after a time the browser/site gets crashed.

I think its cause the size is very big. Is there a way to use pagination and that script only loads like 20 rows and that?

**Comment by areguera** [comment]
Any change to rewrite using https://github.com/mholt/PapaParse ?

**Comment by derekeder** [comment]
related to #53 

look into using `DataTables` server-side: https://datatables.net/manual/server-side
