### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by djibe** [derekeder/csv-to-html-table#68]
Hi everyone,
I created a fork and a Pull request as I did the job to have perfect Bootstrap 4 usage.
Here is my fork for CSV to HTML table with Bootstrap 4 support : https://github.com/djibe/csv-to-html-table

I'll close this issue when @derekeder will merge my Pull request.
Enjoy.

**Comment by derekeder** [comment]
thanks @djibe! PR #67 merged in!
