### ISSUE TITLE
Distribute it via npm

### ISSUE THREAD

**Issue by vvasuki** [derekeder/csv-to-html-table#70]
This seems to be a very good library, but I like to use npm for dependency management. https://www.npmjs.com/search?q=csv-to-html-table&page=0&perPage=20 does not list it though. Mind distributing this via npm?

**Comment by derekeder** [comment]
@vvasuki done: https://www.npmjs.com/package/csv-html-table

This is my first time publishing an npm package, so let me know if there's anything I missed.
