### ISSUE TITLE
How we can use csv file from web via url?

### ISSUE THREAD

**Issue by layymer** [derekeder/csv-to-html-table#74]

**Comment by rturgano** [comment]
I have this question as well. Any updates?

**Comment by GokulNC** [comment]
I created this for that purpose. Hope it helps:
https://github.com/narVidhai/Render-CSV-from-URL-to-HTML-Table

**Comment by derekeder** [comment]
@GokulNC thanks for providing this solution! I don't think I'll bring this option in to this project, though
