### ISSUE TITLE
Adding bootstrap tabs to the view. How would one go about doing this?

### ISSUE THREAD

**Issue by Chriis716** [derekeder/csv-to-html-table#78]
I'm trying to add multiple tabs to my view so I could display different filters depending on the column. How would one add a tab like structure to the build?

Bootstrap tabs example: https://datatables.net/examples/api/tabs_and_scrolling.html

**Comment by derekeder** [comment]
@Chriis716 I would create 2 different instances of `CsvToHtmlTable` - one for each tab
