### ISSUE TITLE
Requested unknown parameter '1' for row 0.

### ISSUE THREAD

**Issue by JannyFoo** [derekeder/csv-to-html-table#8]
Hi,

I periodically export a CSV from MS SQL directly to a web server folder to use with csv-to-html-table. 

I always receive the following when the page loads.
"DataTables warning: table id=my-table - Requested unknown parameter '1' for row 0"

If I open the CSV in Excel and re-save as CSV then the page loads without errors. Any ideas?

I thought it may have something to do with encoding of the CSV from SQL? 

Thanks,
John

**Comment by derekeder** [comment]
@JannyFoo sounds like it must be a formatting issue from MS SQL. Do you have an example you could link to?

**Comment by anagha-todalbagi** [comment]
@JannyFoo : When I got the same error, I commented out the following line,
data = data.replace(/[\r|\r\n]/g, "\n"); //from js/csv_to_html_table.js
This worked perfectly for me.

@derekeder - Neat job! This is very useful, thank you so much!
