### ISSUE TITLE
Cannot work in PHP

### ISSUE THREAD

**Issue by GA-1101** [derekeder/csv-to-html-table#84]
I use this code in PHP webpage file and cannot get the data from csv file. I inset `<?php echo $ID?>` into `csv_path` and the script cannot work to get data from csv file successfully. But transferring the php code into static path can be worked. 

Code can work successfully:
`csv_path: "job/maEjCdPgDZ/download/Results/output.csv",`

Code cannot work:
`csv_path: "job/<?php echo $ID?>/download/Results/output.csv",`
(The character `maEjCdPgDZ` is dynamic which was generated by php script.)

I have checked the web source of webpage in Browser and my ID character is normally in path like `csv_path: "job/maEjCdPgDZ/download/Results/output.csv",` but the page cannot display the content in csv.

**Comment by derekeder** [comment]
this is outside the scope of this project
