### ISSUE TITLE
Can we use multiple CSV once?

### ISSUE THREAD

**Issue by BryarGH** [derekeder/csv-to-html-table#85]
Hello, this is not an issue, it is just an idea or a question that I didn't discover yet. 

Does it have an option to load multiple CSV once?

**Comment by derekeder** [comment]
no, the library doesn't support this. i would recommend merging the CSV files into one yourself in a separate step before using it with this

**Comment by shipurjan** [comment]
![image](https://user-images.githubusercontent.com/57770826/221355499-0ed78b57-472b-413a-a331-042a4dde28ec.png)
I just used two init functions to initialize them, but it's not how it's intended to be used (however in my case it doesn't make any problems)
