### ISSUE TITLE
Table not showing

### ISSUE THREAD

**Issue by qaninjauk** [derekeder/csv-to-html-table#89]
Hi I can't see the table in the browser  Am i doing something wrong?  

the heading and footer but no the table.

Many thanks in advance,

Gwyn
![Screenshot 2022-08-31 at 15 19 19](https://user-images.githubusercontent.com/111118074/187701490-1a27e3b6-f579-4e33-a61e-0ca1f9d8a7f2.png)

**Comment by mikecasas** [comment]
What's your path to the data?

**Comment by Prithwis-2023** [comment]
same problem. Although my path is correct. I even cloned the repo and found that the HTML file doesn't display the table.

**Comment by mikecasas** [comment]
I downloaded the repo and it work fine. Can you open the dev tools and see if there are any errors?

**Comment by Prithwis-2023** [comment]
Are there any of the files that are hidden for the rest of the developers?

**Comment by tabbott36** [comment]
Hi, I was having the same issue and wanted to share what I was doing wrong. 

After cloning the repo, simply opening the html file gave me the same result (text but no table). However, as the instructions suggest, you have to run `python -m SimpleHTTPServer` and then click this link: [http://localhost:8000/](http://localhost:8000/). From there, navigate to the "csv-to-html-table" directory and open the "index.html" file. I'm very new to this so I didn't realise running `python -m SimpleHTTPServer`  was a necessary step. Hopefully this helps others who are having the same issue! Thanks to the authors for such a great service!

**Comment by Prithwis-2023** [comment]
nice!

**Comment by derekeder** [comment]
looks like this was an issue getting it to run locally, which is documented in the instructions
